# **Numpy Funções Básicas**

In [112]:
import numpy as np

Criando um array em Numpy

In [113]:
temp1 = [1, 5, 6, 4, 5]
temp2 = [1.1, 6.2, 5.3, 4.4, 8.5]

## Criando arrays

In [114]:
a = np.array(temp1)
b = np.array(temp2)

print(temp1)
print(temp2)

## Printando os arrays com as "vírgulas", colocando o valor atribuído no array

[1, 5, 6, 4, 5]
[1.1, 6.2, 5.3, 4.4, 8.5]


In [115]:
print(a)
print(b)

## Printando os arrays sem as "vírgulas", colocando a variável do array

[1 5 6 4 5]
[1.1 6.2 5.3 4.4 8.5]


Descrevendo o type de array

In [116]:
a.dtype ## Palavra reservada para identificar o tipo do array

dtype('int64')

In [117]:
b.dtype ## Palavra reservada para identificar o tipo do array

dtype('float64')

Criando um array de forma manual usando o dtype

In [118]:
c = np.array([[1, 2, 3], [4, 5, 6]], dtype='float64') ## Fazendo um array (2, 3) = (linha, coluna), colocando para o float

In [119]:
c

array([[1., 2., 3.],
       [4., 5., 6.]])

In [120]:
c.dtype ## Palavra reservada para identificar o tipo do array

dtype('float64')

Mostrando o formato do array (linha, coluna)

In [121]:
c.shape ## Palavra reservada para a forma do array

(2, 3)

Determinando a dimensão do array

In [122]:
c.ndim ## Palavra reservada para dizer a dimensão do array

2

Mostrando o números de elementos no array

In [123]:
c.size ## Palavra reservada para dizer o tamanho do array

6

descrevendo o tipo da variável

In [124]:
type(c) ## Palavra reservada para dizer o tipo do array

numpy.ndarray

Criando uma matriz 3x4 com todos os elementos nulos e do tipo inteiro

In [125]:
np.zeros((3,4), dtype='int64') ## Palavra reservada para tranformar todos os elementos do array em zero e com o número inteiro

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Criando uma matrix 4x5 com todos os elementos iguais a 1 do tipo float

In [126]:
np.ones((4,5), dtype='float64') ## Palavra reservada para tranformar todos os elementos do array em um e com o número float

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Criando uma matrix 3x3 com todos os elementos iguais a 5

In [127]:
np.full((3, 3), 5) ## Palavra reservada para deixar a matriz com o número único

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

Criando uma matriz 3x3 identidade

In [128]:
np.eye(3,3) ## Palavra reservada para deixar os elementos em diagonal iguais

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Somando elementos do array com um número constante (+2)

In [129]:

np.array([1, 2, 3]) + 2 ## Somando um array com um número qualquer

## (0) 2 + 1 = 3
## (1) 2 + 2 = 4
## (2) 2 + 3 = 5
## (R)[3, 4, 5]

array([3, 4, 5])

Somando dois arrays de tamanhos iguais

In [130]:
np.array([1, 2, 3]) + np.array([1, 2, 3]) ## Somando dois arrays

array([2, 4, 6])

In [131]:
a = np.array([1, 2, 3])
b = np.array([2, 3])
c = np.array([4, 5, 6])

In [132]:
a + b ## Não pode somar devido ao número inferior de elemento  na colunas impossibilitando a soma de a + b 

ValueError: ignored

In [133]:
a + c ## Faz a soma devido ao número exato de elementos na soma dos arrays a + c

array([5, 7, 9])

Somando os arrays comparando as suas formas(shape) utilizando o método de condicional 

In [134]:
if(a.shape == b.shape):
  print("Soma doas arrays realizadas", a + b)
else:
  print("Impossível realizar a soma dos arrays")


Impossível realizar a soma dos arrays


In [135]:
if(a.shape == c.shape):
  print("Soma dos arrays realizadas: ", a + c)
else:
  print("Impossível realizar a soma dos arrays")

Soma dos arrays realizadas:  [5 7 9]


Somando arrays em 2D

In [136]:
a = np.array([[1, 2, 3], [4, 5, 6]])
          ##      +          +
b = np.array([[1, 2, 3], [4, 5, 6]])

In [137]:
print(a)
print(b)

## Imprimindo os arrays

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [138]:
a + b ## Soma

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [139]:
a - b ## Subtração

array([[0, 0, 0],
       [0, 0, 0]])

In [140]:
a / b ## Divisão

array([[1., 1., 1.],
       [1., 1., 1.]])

In [141]:
a * b ## Multiplicação

array([[ 1,  4,  9],
       [16, 25, 36]])

Adicionando o elemento no array

In [142]:
temp = [1, 2, 3, 4]

In [143]:
temp.append(5) # Palavra reservada para adicionar um elemento

In [144]:
temp ## (0) [1, 2, 3, 4, x]

[1, 2, 3, 4, 5]

Removendo o elemento do array

In [145]:
np.delete(temp, 2) ## remove o elemento no índice 2 - [0, 1, 2, 3, 4]

## (0) [1, 2, x, 4, 5]

array([1, 2, 4, 5])

Produto escalar de dois arrays

In [146]:
array1 = [1, 2, 3, 4]
array2 = [5, 6, 7, 8]

In [147]:
array3 = np.dot(array1, array2) ## Multiplicação das duas matrizes

In [148]:
array3

## 1 * 5 = 5 || 2 * 6 = 12 || 3 * 7 = 21 || 4 * 8 = 32
## 5 + 12 + 21 + 32 = 70

70

Soma dos elementos do array

In [149]:
array = ([[1, 2, 3], [4, 5, 6]])

In [150]:
print(np.sum(array))

## 1 + 4 + 2 + 5 + 3 + 6 = 21

21


In [151]:
print(np.sum(array, axis = 0))

## (0) [1, 2, 3] 
## (1) [4, 5, 6]
##      +  +  +
## (R) [5, 7, 9]

[5 7 9]


In [152]:
print(np.sum(array, axis = 1))

## 1 + 2 + 3 = 6
## 4 + 5 + 6 = 15

[ 6 15]


Transposta de uma matriz(array)

In [153]:
transposta = np.array([[1, 2, 3], [4, 5, 6]])

In [154]:
print(transposta) ## Array normal
print(transposta.T) ## Altera as linhas do arras para as colunas 

## (0) [1, 2, 3]
## (1) [4, 5, 6]

## (0) [1, 4]
## (1) [2, 5]
## (2) [3, 6]

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


Utilizando condicionais

In [155]:
arrayCondicao = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10 , 11, 12, 13, 14, 15])

In [156]:
arrayCondicao[arrayCondicao > 5]

## Exibe elementos maiores que 5  (6  7  8  9  10  11  12  13  14  15)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [157]:
arrayCondicao[(arrayCondicao > 5) & (arrayCondicao < 9)]

## Exibe os elementos entre 5 e 9   (6  7  8)

array([6, 7, 8])

In [158]:
arrayCondicao[(arrayCondicao < 5) | (arrayCondicao > 10)]

## Exibe os elementos entre 5 ou 10  (1  2  3  4  11  12  13  14  15)
                                ##         5             10

array([ 1,  2,  3,  4, 11, 12, 13, 14, 15])

Exibindo índices específicos

In [159]:
indice = [1, 2, 3, 4, 5, 6]

In [160]:
indice[2]  ## Mostra o elemento do array referente ao índice [1, 2, 3, x, 5, 6]

3

In [161]:
indice[-1]  ## Mostra o último elemento do array [1, 2, 3, 4, 5, x]

6

In [162]:
indice[-3:] ## Mostra o elemento no índice -3  [1, 2, 3, x, x, x]
                                           ##           [4, 5, 6]

[4, 5, 6]

In [163]:
indice[:-3] ## Mostra o elemento no índice -3  [x, x, x, 4, 5, 6]
                                           ##  [1, 2, 3]

[1, 2, 3]

In [164]:
indice2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [165]:
indice[0] ## Mostra apenas um elemento do array

1

In [166]:
indice2[:,2] ## Mostra os elementos da linha [0, 1] de acordo com o índice no array
                                    ##  (0) [1, 2, [3], 4]
                                    ##  (1) [5, 6, [7], 8]

array([3, 7])

In [167]:
                                                ## (0) [1, 2, 3, 4]
indice2[0,:] ## Mostra todos os elementos da linha (1) [5, 6, 7, 8] de acordo com o índice no array
                                                ## (R) [1, 2, 3, 4]

array([1, 2, 3, 4])

In [168]:
                                                ## (0) [1, 2, 3, 4]
indice2[1,:] ## Mostra todos os elementos da linha (1) [5, 6, 7, 8] de acordo com o índice no array
                                                ## (R) [5, 6, 7, 8]

array([5, 6, 7, 8])

Invertendo valores do array

In [169]:
indice[::-1] ## Invertendo os elementos do array índice
             ##  (0) [1, 2, 3, 4, 5, 6]
             ##  (R) [6, 5, 4, 3, 2, 1]

[6, 5, 4, 3, 2, 1]

In [170]:
indice2[::-1] ## Invertendo os elementos do arra índice2
              ## (0) [1, 2, 3, 4]
              ## (1) [5, 6, 7, 8]
              
              ## (R) [5, 6, 7, 8]
              ## (R) [1, 2, 3, 4]

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])